# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4f95d7e3daea159dc8a758d9ac4f5d7126355d5cb38614b8692e16dfed8f5d4e6e4b1d224402cd3ba6deb7e2d0fa1ac6d4471677ca1d8a5787651365f458be6b

test:
  secret_key_base: feb55d58ffc9c992f683a1aabf45ac152e54976192eeaaa864b78a20722f1791a0fdf04540a28796cd4f2b7e959f54dc8e5b8f997b25386d7f72337a5c841c61

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
